config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'
  get 'categories/show'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/edit'
  root to: 'pages#home'

  get '/artists', to: 'pages#helloWorld', as: 'helloWorld'
  get '/about', to: 'about#info', as: 'info'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/concerns/post.rb
class Post < ApplicationRecord


end

app/controllers/about_controller.rb
class AboutController < ApplicationController

    def info
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to category_path(@category.id)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    redirect_to category_path(@category.id)
  end

  def edit
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def helloWorld
        @name = params[:name]
    end

    def home
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/info.html.erb
<header>
    <h2>About this website</h2>
</header>

<div>
    <h4>This website was made to learn Ruby on Rails 6</h4>
    <h4>I made this type of website to promote the artists I like</h4>
    <h4>I also draw since a long time but I am a dummy</h4>
</div>

<footer>
    <h4>I hope you enjoy this website and discover some artists</h4>
    <h4>If you want to tell me anything, discord tag : Amaya#0139</h4>
    <h4><a href="https://github.com/AmayaHena/Waifu">Github Repo</a></h4>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">
          <a href="<%= root_path %>"><h1>WAIFU</h1></a>
        </h3>
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link" href="<%= helloWorld_path%>">ARTISTS</a>
          <a class="nav-link" href="<%= info_path %>">ABOUT</a>
        </nav>
      </div>
    </header>

  </body>

  <div class="container" style="padding-top: 5rem;">
    <%= yield %>
  <div>
</html>

app/views/pages/helloWorld.html.erb
<header>
    <h4>Respect the Artists please, go check their work</h4>
    <h4>Click on their name</h4>

    <div class="main" id="section1">
    <a href="#section2"></a>
    </div>
</header>


<%#-------------------------------%>
<%#----------- SAMPLE ------------%>
<%#-------------------------------%>

<%#
<div class="wrapper>">
    <a href="" class="clip-text clip-text_one"></a>
</div>
%>

<div>
    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=11246082" class="clip-text clip-text_one">Miv4t</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=420928" class="clip-text clip-text_two">LM7</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=648285" class="clip-text clip-text_tree">mocha</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=2131660" class="clip-text clip-text_four">pote</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=1980643" class="clip-text clip-text_five">ASK</a>
    </div>

    <div class="wrapper>">
        <a href="https://twitter.com/fluffy2038?fbclid=IwAR1B7mk1jmldVygeIpOk2VDDWxUIBzost7yx8BX3hJsI6X-KJIpXlE-PZ1k" class="clip-text clip-text_six">トーコ</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=6822047" class="clip-text clip-text_seven">人米</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=1056186" class="clip-text clip-text_eight">catzz</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=777703" class="clip-text clip-text_nine">neco</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=10710834" class="clip-text clip-text_ten">novelance</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=5130774" class="clip-text clip-text_eleven">SMAV</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=4819066" class="clip-text clip-text_twelve">T5</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=19029917" class="clip-text clip-text_thirdteen">tamaki</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/users/17429" class="clip-text clip-text_fourteen">LAM</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/member.php?id=1096314" class="clip-text clip-text_fiveteen">桜木蓮</a>
    </div>

    <div class="wrapper>">
        <a href="https://www.pixiv.net/en/users/35081" class="clip-text clip-text_sixteen">Tiv</a>
    </div>
</div>

<footer>
    <h4>Always be respectfull, and notice them</h4>

    <div class="main" id="section2">
    <a href="#section1" class="button2">Top</a>
    </div>
    <br/>
</footer>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>

    <label>Name</label>
    <div id="name", class="form-group">
        <%= f.text_field :name, class: 'input'%>
    </div>

    <label>Content</label>
    <div id="post", class="form-group">
        <%= f.text_field :content, class: 'input'%>
    </div>

    <div class="form-group">
        <a href="<%= post_path %>" class="button1">Back to <%= @post.name %></a>
        <button type="submit" class="button1">Edit Post</button>
    </div>

<% end %>

app/views/posts/index.html.erb
<header>
    <h3>Updates</h3>
    <h3>Be respectfull.</h3>
</header>

<div>
    <% @posts.each do |post| %>
        <h2><%= post.name %> | <%= post.content %></h2>
        <p><a href="<%= post_path(post.id) %>" class="button2">Read more</a></p>
    <% end %>
</div>

<footer>
    <a href="<%= new_post_path %>" class="button1">New Post</a>
</footer>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

    <label>Name</label>
    <div id="name", class="form-group">
        <%= f.text_field :name, class: 'input'%>
    </div>

    <label>Content</label>
    <div id="post", class="form-group">
        <%= f.text_field :content, class: 'input'%>
    </div>

    <div class="form-group">
        <a href="<%= posts_path %>" class="button1">Back to <%= @post.name %></a>
        <button type="submit">Create Post</button>
    </div>

<% end %>

app/views/posts/show.html.erb
<header>
    <h2><%= @post.name %></h2>
    <p><%= @post.content %></p>
</header>

<p>
    <a href="<%= posts_path %>" class="button1">Back</a>
    <a href="<%= request.path+"/edit" %>" class="button1">Edit</a>
    <a class="button2" data-confirm="Delete ?" data-method="DELETE">Delete</a>
    <%= csrf_meta_tags %>
</p>